### PR TITLE
Pull data from google images & quality of life update

### PR DESCRIPTION
**Pull request by lithomas1**
Objectives:
- Autodataset generator
- Tensorboard

### CODE REVIEW

**Comment by lithomas1** [comment]
@KentoNishi 
Can you plz add tensorboard? I kind of did it but not really.

**Comment by KentoNishi** [comment]
Not today! After finals.

**Comment by lithomas1** [comment]
> 
> 
> Not today! After finals.

never mind. got it 💯

**Comment by lithomas1** [comment]
hey @KentoNishi , 
can you please test the tensorboard image display functionality? 
Thanks,
Thomas

**Pull request merged**
