### PR TITLE
Implement Python functions in C++

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by KentoNishi** [comment]
But why

**Comment by lithomas1** [comment]
> 
> 
> But why

c is yeet

**Comment by KentoNishi** [comment]
But TensorFlow and Keras only support Python

**Comment by lithomas1** [comment]
> 
> 
> > But why
> 
> c is yeet, also i want to learn c++ lol

because of the slow stuff.

**Comment by KentoNishi** [comment]
C++ is pretty straightforward, it'll be easy
Also, how the heck are we going to use C++ for Keras?

**Comment by lithomas1** [comment]
> 
> 
> C++ is pretty straightforward, it'll be easy
> Also, how the heck are we going to use C++ for Keras?

we use python

**Comment by KentoNishi** [comment]
I Am CoNfUsIoN?

**Comment by lithomas1** [comment]
> 
> 
> > C++ is pretty straightforward, it'll be easy
> > Also, how the heck are we going to use C++ for Keras?
> 
> we use python



> 
> 
> I Am CoNfUsIoN?

converting images into numpy arrays and downloading them is done in c++ in this branch. ML is done in python

**Comment by KentoNishi** [comment]
We should set up a web server for ssh so Rahul and Alex can access the Jetson too

**Comment by lithomas1** [comment]
k. will set up post request service for sudocodewebsite

**Comment by KentoNishi** [comment]
Wait nevermind ssh in JS is really hard

**Comment by lithomas1** [comment]
> 
> 
> Wait nevermind ssh in JS is really hard

dJAngo

**Comment by KentoNishi** [comment]
Can you make a new repo with a basic django script deployed to heroku?

**Pull request closed without merging**
